import io
import re
from xml.sax.saxutils import escape

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, Inches
from fpdf import FPDF


def sanitize_text(text: str) -> str:
    """Remove problematic typographic/special characters."""
    replacements = {
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2013": "-",
        "\u2014": "-",
        "\u00a0": " ",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return escape(text).replace("\n", "<br>")


def format_txt(text: str) -> bytes:
    return text.encode("utf-8")


def _add_content_to_doc(document, text):
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            document.add_paragraph()
            continue

        if re.match(r"^(ARTICLE|SECTION|\d+[\.\)]|[A-Z][A-Z\s&-]{4,})", line):
            p = document.add_paragraph()
            run = p.add_run(line)
            run.bold = True
            run.font.name = "Times New Roman"
            run.font.size = Pt(12)
        else:
            p = document.add_paragraph(line)
            for run in p.runs:
                run.font.name = "Times New Roman"
                run.font.size = Pt(11)


def format_docx(text: str, doc_type: str) -> bytes:
    document = Document()
    section = document.sections[0]
    section.top_margin = Inches(0.7)
    section.bottom_margin = Inches(0.7)
    section.left_margin = Inches(0.8)
    section.right_margin = Inches(0.8)

    title = document.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run(doc_type.upper())
    run.bold = True
    run.font.name = "Times New Roman"
    run.font.size = Pt(16)

    _add_content_to_doc(document, text)

    footer = section.footer.paragraphs[0]
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer.add_run("Generated by LegalEase").font.name = "Times New Roman"

    buffer = io.BytesIO()
    document.save(buffer)
    return buffer.getvalue()


class LegalEasePDF(FPDF):
    def __init__(self, doc_type):
        super().__init__()
        self.doc_type = doc_type
        self.set_auto_page_break(auto=True, margin=18)

    def header(self):
        self.set_font("Helvetica", "B", 13)
        self.cell(0, 8, self.doc_type, align="C")
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "", 8)
        self.cell(0, 8, "Generated by LegalEase", align="C")


def format_pdf(text: str, doc_type: str) -> bytes:
    pdf = LegalEasePDF(doc_type)
    pdf.add_page()
    pdf.set_font("Helvetica", size=11)

    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            pdf.ln(4)
            continue

        is_heading = bool(
            re.match(r"^(ARTICLE|SECTION|\d+[\.\)]|[A-Z][A-Z\s&-]{4,})", line)
        )

        if is_heading:
            pdf.set_font("Helvetica", "B", 11)
        else:
            pdf.set_font("Helvetica", "", 11)

        pdf.multi_cell(0, 6, line)

    return bytes(pdf.output(dest="S"))
